WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

sentence = _{ token+ }
token = _{ word | punctuation }
word = @{ wordchar+ }

wordchar = { ASCII_ALPHA | "'" | "-" }
punctuation = @{ 
    "." | "," | ";" | ":" | "!" | "?" | 
    "(" | ")" | "[" | "]" | "{" | "}" | 
    "\"" | "'" | "-" | "—" | "–" | 
    "..." | ".." | 
    "/" | "\\" | 
    "&" | "@" | "#" | "%" | "^" | "*" | "+" | "=" | "_" | "~" | "`" |
    "<" | ">"
}
